package com.core.entities;
// Generated 03/09/2016 23:20:16 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entry generated by hbm2java
 */
@Entity
@Table(name="entry"
    ,schema="public"
)
public class Entry  implements java.io.Serializable {


     private EntryId id;
     private Project project;
     private Date date;
     private String content;
     private String title;

    public Entry() {
    }

	
    public Entry(EntryId id, Project project, String title) {
        this.id = id;
        this.project = project;
        this.title = title;
    }
    public Entry(EntryId id, Project project, Date date, String content, String title) {
       this.id = id;
       this.project = project;
       this.date = date;
       this.content = content;
       this.title = title;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false, length=64) ), 
        @AttributeOverride(name="idProject", column=@Column(name="id_project", nullable=false, length=64) ) } )
    public EntryId getId() {
        return this.id;
    }
    
    public void setId(EntryId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_project", nullable=false, insertable=false, updatable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=35)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="content")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="title", nullable=false, length=512)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


