package com.core.entities;
// Generated 03/09/2016 21:35:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
    ,schema="public"
)
public class Project  implements java.io.Serializable {


     private String id;
     private String name;
     private String description;
     private Set entries = new HashSet(0);

    public Project() {
    }

	
    public Project(String id, String name) {
        this.id = id;
        this.name = name;
    }
    public Project(String id, String name, String description, Set entries) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.entries = entries;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=64)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=1024)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project")
    public Set getEntries() {
        return this.entries;
    }
    
    public void setEntries(Set entries) {
        this.entries = entries;
    }




}


